### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jerrydengz** [jerrydengz/kdrama_database.cmpt135#23]
- [x] Finalize `Deleting` functions for genre, actors
- [x] Do `Deleting` functions for the `Status` fields
- [x] Start `Editing` functions
- [x] Decide what to do with searching & deleting `Total Eps`  field
- [x] Decide if want to delete a single record or all records for `range_year()` & `range_rating()`
- [x] File In system (`file.h` & `file.cpp`)
- [x] File Out system (`file.h` & `file.cpp`)
- [x] create test file data of records
- [x] sort the vector<string> fields (genre & actors) alphabetically before adding them as a record field
- [x] Login system for `file.h` & `file.cpp`
- [x] figure out `<ncurses.h>`
- [x] `Menu.h`
- [x] Testing
